apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  namespace: p-kwmx9-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:stable
        name: nginx
        ports:
        - containerPort: 80
          hostPort: 8082
          name: nginxport1
          protocol: TCP 
      dnsPolicy: ClusterFirst
